<a href="https://colab.research.google.com/github/riccardocappi/Machine_Learning_Course/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Riccardo Cappi, 2073768**

In [ ]:
import numpy as np
from itertools import product
from random import randrange
from random import choice

###Perceptron Class###

In [ ]:
class Perceptron:
  def __init__(self,data,t,lr,steps):
    self.lr = lr
    self.data = data
    self.steps = steps
    self.S = list(zip(data,t))

  def compute(self,x,w,b):
    net = np.dot(x,w) + b
    o = 0 if net < 0 else 1
    return o


  def learn(self):
    w = np.random.rand(self.data.shape[1]+1)
    for _ in range(self.steps):
      x,t = choice(self.S)
      x = np.asarray([1] + list(x))
      o = self.compute(x[1:],w[1:], w[0])
      if not o == t:
        #Learning
        w += self.lr*(t-o)*x
    return w[0], w[1:]

In [ ]:
def test(formula, steps, lr):
  data = list(product((0,1),repeat=3))
  data = np.array(data)
  t = [formula(*s) for s in data]

  p = Perceptron(data,t,lr, steps)
  bias,weights = p.learn()
  print('Learning concluded\n')
  print('Expected output: ')
  for d in data:
    print(d, '->', formula(*d))

  print('\nbias: ',bias)
  print('weights: ', weights)
  print('\nPredicted output: ')
  for d in data:
    res = p.compute(d,weights,bias)
    print(d,'->',res)

###Test on 'AND' formula###

In [ ]:
AND = lambda x1,x2,x3: int(x1 and x2 and x3)

#Test 'AND' formula
test(AND,500,0.1)


Learning concluded

Expected output: 
[0 0 0] -> 0
[0 0 1] -> 0
[0 1 0] -> 0
[0 1 1] -> 0
[1 0 0] -> 0
[1 0 1] -> 0
[1 1 0] -> 0
[1 1 1] -> 1

bias:  -0.782102468496333
weights:  [0.21209347 0.18242865 0.46320426]

Predicted output: 
[0 0 0] -> 0
[0 0 1] -> 0
[0 1 0] -> 0
[0 1 1] -> 0
[1 0 0] -> 0
[1 0 1] -> 0
[1 1 0] -> 0
[1 1 1] -> 1


###Test on 'OR' formula###


In [ ]:
OR = lambda x1,x2,x3: int(x1 or x2 or x3)
test(OR,500,0.1)

Learning concluded

Expected output: 
[0 0 0] -> 0
[0 0 1] -> 1
[0 1 0] -> 1
[0 1 1] -> 1
[1 0 0] -> 1
[1 0 1] -> 1
[1 1 0] -> 1
[1 1 1] -> 1

bias:  -0.03385875653626755
weights:  [0.63676154 0.74545363 0.2396836 ]

Predicted output: 
[0 0 0] -> 0
[0 0 1] -> 1
[0 1 0] -> 1
[0 1 1] -> 1
[1 0 0] -> 1
[1 0 1] -> 1
[1 1 0] -> 1
[1 1 1] -> 1


###Test on 'XOR' formula###
Even with a very high number of learning steps, the algorithm isn't able to predict the 'XOR' formula


In [ ]:
def XOR(x1,x2,x3):
  a = (x1 and (not x2)) or ((not x1) and x2)
  return int((a and (not x3)) or ((not a) and x3))
test(XOR,5000,0.1)

Learning concluded

Expected output: 
[0 0 0] -> 0
[0 0 1] -> 1
[0 1 0] -> 1
[0 1 1] -> 0
[1 0 0] -> 1
[1 0 1] -> 0
[1 1 0] -> 0
[1 1 1] -> 1

bias:  0.003940397023797976
weights:  [-0.04978802  0.07561698  0.02045778]

Predicted output: 
[0 0 0] -> 1
[0 0 1] -> 1
[0 1 0] -> 1
[0 1 1] -> 1
[1 0 0] -> 0
[1 0 1] -> 0
[1 1 0] -> 1
[1 1 1] -> 1


###Changing learning rate and number of steps###
In the following cell i'll show how the behavior of the Perceptron changes with different values of learning rate and number of steps

Let's consider the 'AND' formula

In [ ]:
AND = lambda x1,x2,x3: int(x1 and x2 and x3)
values = [ (100, 0.01), (500,0.01), (300, 0.1), (300, 0.001) ]
for v in values:
  print('Test with number of steps = ',v[0],'and learning rate = ', v[1])
  test(AND,*v)
  print('---------------------------------------------------------------')

Test with number of steps =  100 and learning rate =  0.01
Learning concluded

Expected output: 
[0 0 0] -> 0
[0 0 1] -> 0
[0 1 0] -> 0
[0 1 1] -> 0
[1 0 0] -> 0
[1 0 1] -> 0
[1 1 0] -> 0
[1 1 1] -> 1

bias:  -0.31999318842660623
weights:  [ 0.45157813  0.0415308  -0.00917164]

Predicted output: 
[0 0 0] -> 0
[0 0 1] -> 0
[0 1 0] -> 0
[0 1 1] -> 0
[1 0 0] -> 1
[1 0 1] -> 1
[1 1 0] -> 1
[1 1 1] -> 1
---------------------------------------------------------------
Test with number of steps =  500 and learning rate =  0.01
Learning concluded

Expected output: 
[0 0 0] -> 0
[0 0 1] -> 0
[0 1 0] -> 0
[0 1 1] -> 0
[1 0 0] -> 0
[1 0 1] -> 0
[1 1 0] -> 0
[1 1 1] -> 1

bias:  -0.46435639121950195
weights:  [0.02180461 0.34514369 0.09790242]

Predicted output: 
[0 0 0] -> 0
[0 0 1] -> 0
[0 1 0] -> 0
[0 1 1] -> 0
[1 0 0] -> 0
[1 0 1] -> 0
[1 1 0] -> 0
[1 1 1] -> 1
---------------------------------------------------------------
Test with number of steps =  300 and learning rate =  0.1
Learning conc

As you can see, with a small learning rate (i.e 0.01) you have to increase the number of learning steps in order to get a correct prediction.

On the other hand, even with an high number of learning steps (i.e 300), a learning rate too small (i.e 0.001) can cause a misprediction